config/routes.rb
Rails.application.routes.draw do
  get 'contest/index'
  get 'contest/new'
  get 'contest/created'
  post 'contest/create'
  get 'contest/show'
  get 'contest/edit'
  put 'contest/update'
  delete 'contest/destroy'
  #devise_for :contests
  #devise_for :installs
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        confirmations: 'users/confirmations',
        unlocks: 'users/unlocks',
        passwords: 'users/passwords'
      }, path_names: {
        sign_in: 'login',
        sign_out: 'logout',
        password: 'secret',
        registrations: 'register',
        confirmations: 'verification',
        sign_up: 'signup'
      }
    
  devise_scope :user do
      get '/users/logout' => 'users/sessions#destroy', as: "user_signout" 
    end

  resources :places
  resources :riders
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/home-home' => 'home#home'
  get '/pages-about' => 'pages#about'
  get '/pages-photo' => 'pages#photo'
  get '/pages-location' => 'pages#location'
  get '/contest-contest' => 'contest#contest'
  get '/riders' => 'riders#riders'

  root to: "home#home"

end

app/models/contest.rb
class Contest < ApplicationRecord
end

app/controllers/contest_controller.rb
class ContestController < ApplicationController
  def index
  end

  def created
  end

  # GET /contest/new
  def new
    @contest = Contest.new
  end

  # POST /contest/create
  def create
    @contest = Contest.create(params.require(:contest).permit(:firstname, :lastname, :email, :slogan))
    redirect_to contest_created_url
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/contest_helper.rb
module ContestHelper
end

app/views/contest/created.html.erb
<div class="container my-5 py-5">

    <h4 class="bg-success text-white p-2"> Your Slogan has been Saved </h4>
</div>

app/views/contest/destroy.html.erb
<h1>Contest#destroy</h1>
<p>Find me in app/views/contest/destroy.html.erb</p>

app/views/contest/edit.html.erb
<h1>Contest#edit</h1>
<p>Find me in app/views/contest/edit.html.erb</p>

app/views/contest/index.html.erb
<h1>Contest#index</h1>
<p>Find me in app/views/contest/index.html.erb</p>

app/views/contest/new.html.erb
<div class="container my-5 py-5">

    <h4> Enter the Slogan Contest </h4>

    <%= form_for @contest, url: contest_create_url(@contest) do |form| %>

  <div class="container" style="margin-top: 50px">
    <div class="field">
      <div class="form">
        <p>
          <%= form.label :firstname %>
          <%= form.text_field :firstname, required: true, class: "form-control w-50" %>
        </p>

        <p>
          <%= form.label :lastname %>
          <%= form.text_field :lastname, required: true, class: "form-control w-50" %>
        </p>

        <p>
          <%= form.label :email %>
          <%= form.email_field :email, required: true, class: "form-control w-50"  %>
        </p>

        <p>
          <%= form.label :slogan %>
          <%= form.text_field :slogan, required: true, class: "form-control w-50" %>
        </p>

        

        <div class="actions w-25">
            <%= form.submit "Submit Slogan",  class: "btn btn-lg btn-primary btn-block"  %>
        </div>

      </div>
    </div>
  </div>

<% end %>

</div>

app/views/contest/show.html.erb
<h1>Contest#show</h1>
<p>Find me in app/views/contest/show.html.erb</p>

app/views/contest/update.html.erb
<h1>Contest#update</h1>
<p>Find me in app/views/contest/update.html.erb</p>