config/routes.rb
Rails.application.routes.draw do
  get 'contest/index'
  get 'contest/new'
  get 'contest/created'
  post 'contest/create'
  get 'contest/show'
  get 'contest/edit'
  put 'contest/update'
  delete 'contest/destroy'
  #devise_for :contests
  #devise_for :installs
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        confirmations: 'users/confirmations',
        unlocks: 'users/unlocks',
        passwords: 'users/passwords'
      }, path_names: {
        sign_in: 'login',
        sign_out: 'logout',
        password: 'secret',
        registrations: 'register',
        confirmations: 'verification',
        sign_up: 'signup'
      }
    
  devise_scope :user do
      get '/users/logout' => 'users/sessions#destroy', as: "user_signout" 
    end

  resources :places
  resources :riders
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/home-home' => 'home#home'
  get '/pages-about' => 'pages#about'
  get '/pages-photo' => 'pages#photo'
  get '/pages-location' => 'pages#location'
  get '/contest-contest' => 'contest#contest'
  get '/riders' => 'riders#riders'

  root to: "home#home"

end

app/models/rider.rb
class Rider < ApplicationRecord
end

app/controllers/riders_controller.rb
class RidersController < ApplicationController
  before_action :set_rider, only: [:show, :edit, :update, :destroy]

  # ) /riders
  # GET /riders.json
  def index
    @riders = Rider.all
  end

  # GET /riders/1
  # GET /riders/1.json
  def show
  end

  # GET /riders/new
  def new
    @rider = Rider.new
  end

  # GET /riders/1/edit
  def edit
  end

  # POST /riders
  # POST /riders.json
  def create
    @rider = Rider.new(rider_params)

    respond_to do |format|
      if @rider.save
        format.html { redirect_to @rider, notice: 'Rider was successfully created.' }
        format.json { render :show, status: :created, location: @rider }
      else
        format.html { render :new }
        format.json { render json: @rider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /riders/1
  # PATCH/PUT /riders/1.json
  def update
    respond_to do |format|
      if @rider.update(rider_params)
        format.html { redirect_to @rider, notice: 'Rider was successfully updated.' }
        format.json { render :show, status: :ok, location: @rider }
      else
        format.html { render :edit }
        format.json { render json: @rider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /riders/1
  # DELETE /riders/1.json
  def destroy
    @rider.destroy
    respond_to do |format|
      format.html { redirect_to riders_url, notice: 'Rider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rider
      @rider = Rider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rider_params
      params.fetch(:rider, {}).permit(:first_name, :last_name, :city_of_origin, :state_of_origin)
    end
end

app/helpers/riders_helper.rb
module RidersHelper
end

app/views/riders/_form.html.erb
<%= form_with(model: rider, local: true) do |form| %>
  <% if rider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rider.errors.count, "error") %> prohibited this rider from being saved:</h2>

      <ul>
      <% rider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container" style="margin-top: 50px">
    <div class="field">
      <div class="form">
        <p>
          <%= form.label :first_name %>
          <%= form.text_field :first_name %>
        </p>

        <p>
          <%= form.label :last_name %>
          <%= form.text_field :last_name %>
        </p>

        <p>
          <%= form.label :city_of_origin %>
          <%= form.text_field :city_of_origin %>
        </p>

        <p>
          <%= form.label :state_of_origin %>
          <%= form.text_field :tate_of_origin %>
        </p>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/riders/edit.html.erb
<h1>Editing Rider</h1>

<%= render 'form', rider: @rider %>

<%= link_to 'Show', @rider %> |
<%= link_to 'Back', riders_path %>

app/views/riders/index.html.erb
<!--================ Riders Area =================-->
<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
      <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
    <div class="container">
      <div class="banner_content text-center">
        <div class="page_link">
          <a href="<%= root_path %>">Home</a>
          <a href="<%= riders_path %>">Riders</a>
          <h2>Riders</h2>
        </div>
      </div>
    </div>
    </div>
</section>


<!--================ End Riders Area =================-->

    <%= render partial: 'layouts/front_end/riders_full' %>

<%# <%= link_to 'New Rider', new_rider_path %> 

<a href="<%= root_path %>">Back</a>

app/views/riders/new.html.erb
<h1>New Rider</h1>

<%= render 'form', rider: @rider %>

<%= link_to 'Back', riders_path %>

app/views/riders/rider_backup.html.erb
<!--================ Riders Area =================-->
<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
      <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
    <div class="container">
      <div class="banner_content text-center">
        <div class="page_link">
          <a href="<%= root_path %>">Home</a>
          <a href="<%= riders_path %>">Riders</a>
          <h2>Riders</h2>
        </div>
      </div>
    </div>
    </div>
</section>


<!--================ End Riders Area =================-->

<div class="container">
  <div class="row">
  <tbody>
    <% @riders.each do |rider| %>
    
      <div class="col-3">
        <div class="team_item">
            <div class="team_img">
              <img class="img-fluid" src="<%= asset_path('eventure/img/team/team-1.jpg') %>" alt="">
            </div>
            <h5><%= link_to rider.first_name %> <%= link_to rider.last_name %></h5>
            <p>rider test</p>
          <tr>
            <td><%= link_to 'Show', rider %></td>
            <td><%= link_to 'Edit', edit_rider_path(rider) %></td>
            <td><%= link_to 'Destroy', rider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        </div>
    </div>
    <% end %>
  </tbody>
</div>
</div>

<%= link_to 'New Rider', new_rider_path %>

<a href="<%= root_path %>">Back</a>

app/views/riders/riders.html.erb
<!--================ Riders Area =================-->
<section class="home_banner_area">
	<div class="banner_inner">
    	<div class="container">
    		<div class="banner_content">
    			<h2>Riders</h2>
    			<p>This is the riders page</p>
    		</div>
    	</div>
    </div>	
</section>

<%= render partial: 'layouts/front_end/riders' %>
<!--================ End Riders Area =================-->

<a href="<%= root_path %>">Back</a>

app/views/riders/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron jumbotron-fluid">  
    <div class="container">
        <div class="row">
          	<div class="col-sm">

				<p><%= @rider.first_name %></p>
				<p><%= @rider.last_name %></p>
				<p><%= @rider.city_of_origin %></p>
				<p><%= @rider.state_of_origin %></p>
			
			</div>
		</div>
	</div>
</div>

<%= link_to 'Edit', edit_rider_path(@rider) %> |
<%= link_to 'Back', riders_path %>